import path from "path";
import { File } from "./file";
import upath from "upath";
import { FrontendPath } from "./frontend-path";
import { Echo } from "./echo";
import shell from "shelljs";
import { Constants } from "./constants";

// -----------------------------------------------------------------------------------------
// #region Variables
// -----------------------------------------------------------------------------------------

const environmentFileName = ".env.local";

// #endregion Variables

// -----------------------------------------------------------------------------------------
// #region Functions
// -----------------------------------------------------------------------------------------

const DeployConfig = {
    /**
     * Generates a local env file with a PUBLIC_URL variable.
     * @param {*} publicUrl the value to set PUBLIC_URL to.
     */
    configurePublicUrl(publicUrl: string) {
        // Delete current file if it exists
        const environmentFilePath = upath.join(
            FrontendPath.projectDir(),
            environmentFileName
        );
        File.deleteIfExists(environmentFilePath);

        // Output environment file configured with 'PUBLIC_URL'
        Echo.message(
            `Generating new ${environmentFilePath} file with contents of...`
        );
        const publicUrlLine = `PUBLIC_URL=${publicUrl}`;
        shell
            .echo(`# File generated by '${Constants.CLI_NAME}'`)
            .toEnd(environmentFilePath);
        shell.echo(publicUrlLine).toEnd(environmentFilePath);
        shell.echo("").toEnd(environmentFilePath);
        Echo.success("Local environment file generated successfully");
    },
};

// #endregion Functions

// -----------------------------------------------------------------------------------------
// #region Exports
// -----------------------------------------------------------------------------------------

export { DeployConfig };

// #endregion Exports
